sudo: false
addons:
  apt:
    packages:
      - libudev-dev

python:
  - "3.5.3"
  - "3.6"
  - "3.7"
  - "3.8-dev"

env:
  - TOXENV=lint
  - TOXENV=pylint
  - TOXENV=typing
  - TOXENV=cov
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=py38

matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      env: TOXENV=lint
    - python: "3.5.3"
      env: TOXENV=pylint
    - python: "3.5.3"
      env: TOXENV=typing
    - python: "3.5.3"
      env: TOXENV=cov
      after_success: coveralls
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
      dist: xenial
    - python: "3.8-dev"
      env: TOXENV=py38
      dist: xenial
      if: branch = dev AND type = push
  allow_failures:
    - python: "3.8-dev"
      env: TOXENV=py38
      dist: xenial

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
stages:
    - test
    - name: transferupload
      if: env(TOXENV) = py37 AND type IN (push, pull_request)
jobs:
  include:
    - stage: test
      script: travis_wait 30 tox --develop
    - stage: transferupload
      script: script/ephemeral_release


