#!/bin/sh
# Pushes a new version to PyPi.

cd "$(dirname "$0")/.."

if ./script/check_release; then
    rm -rf dist
    python3 setup.py sdist bdist_wheel
    python3 -m twine upload dist/* --skip-existing
else
    echo "check_release failed. Aborting release."
fi

